### ISSUE TITLE
how to represent NA in heatmap

### ISSUE THREAD

**Issue by shruti3009** [eacton/Heatmaps#2]
Hi,
Can you suggest a way to plot NA values in the data frame that can be plotted on the pheatmap with different color?

**Comment by eacton** [comment]
Hi @shruti3009 

If you look in the help menu for the pheatmap() function, it actually has an argument 'na_col', which you can set to a color. To show this as an example using the lesson data, below, I have changed a few values to NA, and then show a function call with the argument added (in which the color for NA is set to black).

     genes[1:5, 55] <- NA

     pheatmap(genes[c(1:5, 55:60), c(1:5, 20:35, 55:60)], fontsize = 8, fontsize_row = 6, fontsize_col = 6, 
     cluster_rows = T, cluster_cols = F, annotation_row = annotation_row, annotation_col = 
     annotation_col, na_col = "black", main = "Gene Expression for Drug X Trial for B-Cell vs T-Cell 
     Patients")`
